env: dev
app: cloud-chatops
replicaCount: 3
image:
  repository: harbor.stfc.ac.uk/stfc-cloud/cloud-chatops
  tag: 5.0.1
repos:
  stfc:
    - cloud-deployed-apps
    - st2-cloud-pack
    - cloud-grafana-dashboards
    - cloud-pe-jupyterhub
    - cloud-ops-tools
    - cloud-docker-images
    - cloud-capi-values
    - cloud-image-builders
    - cloud-docs
    - cloud-openstack-horizon
    - ansible-harbor
    - terraform-openstack
    - cloud-rundeck-jobs
    - openstack-guide
    - ansible-jupyter
    - SCD-Openstack-Utils
    - check-version-action
    - cloud-helm-charts
channel: C03RT2F6WHZ
