apiVersion: v2
dependencies:
  - name: galaxy
    repository: https://raw.githubusercontent.com/CloudVE/helm-charts/master/
    version: 6.1.1
  - name: galaxy-deps
    repository: https://raw.githubusercontent.com/CloudVE/helm-charts/master/
    version: 1.0.0
  - name: oauth2-proxy
    repository: https://oauth2-proxy.github.io/manifests
    version: 7.12.13
name: materials-galaxy
version: 2.0.1
