apiVersion: v2
dependencies:
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: v1.19.3
description: A Helm chart to deploy opinionated instance of cert-manager for the STFC Cloud
name: stfc-cloud-cert-manager
type: application
version: 1.2.8
