harbor:
  externalURL: "https://harbor.example.com"
  expose:
    type: ingress
    tls:
      enabled: true
      certSource: auto
      auto:
        commonName: "harbor"
      secret:
        secretName: "selfsigned"
        #secretName: "letsencrypt-prod"
    ingress:
      hosts:
        core: "harbor.example.com"
      controller: default
      ## Allow .Capabilities.KubeVersion.Version to be overridden while creating ingress
      kubeVersionOverride: ""
      className: "nginx"
      annotations:
        # note different ingress controllers may require a different ssl-redirect annotation
        # for Envoy, use ingress.kubernetes.io/force-ssl-redirect: "true" and remove the nginx lines below
        ingress.kubernetes.io/ssl-redirect: "true"
        ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        # Please change cluster issue to prod when you are happy
        cert-manager.io/cluster-issuer: "selfsigned"
        #cert-manager.io/cluster-issuer: "letsencrypt-prod"
      # ingress-specific labels
      labels: {}
  database:
    type: external
    external:
      host: "host.example.com"
      port: "5432"
      coreDatabase: "harbor_registry"
      username: "registry_user"
      # if using existing secret, the key must be "password"
      password: "password"
      # "disable" - No SSL
      # "require" - Always SSL (skip verification)
      # "verify-ca" - Always SSL (verify that the certificate presented by the
      # server was signed by a trusted CA)
      # "verify-full" - Always SSL (verify that the certification presented by the
      # server was signed by a trusted CA and the server host name matches the one
      # in the certificate)
      sslmode: "disable"
    # The maximum number of connections in the idle connection pool per pod (core+exporter).
    # If it <=0, no idle connections are retained.
    maxIdleConns: 100
    # The maximum number of open connections to the database per pod (core+exporter).
    # If it <= 0, then there is no limit on the number of open connections.
    # Note: the default number of connections is 1024 for postgre of harbor.
    maxOpenConns: 900
    ## Additional deployment annotations
    podAnnotations: {}
    ## Additional deployment labels
    podLabels: {}
  jobservice:
    replicas: 2
    jobLoggers:
      - database
  registry:
    replicas: 2
  trivy:
    replicas: 2
  exporter:
    replicas: 2
  portal:
    replicas: 2
  core:
    replicas: 2
  persistence:
    enabled: false
    resourcePolicy: ""
    imageChartStorage:
      disableredirect: false
      type: s3
      s3:
        bucket: bucketname
        accesskey: awsaccesskey
        secretkey: awssecretkey
        regionendpoint: s3.example.com
        encrypt: false
        secure: true
        skipverify: false

  metrics:
    enabled: true
    rules:
      enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus

backup:
  enabled: true
  image: amazon/aws-cli:latest  
  endpoint: "https://s3.example.com"
  sourceBucket: "s3://harbor-source-bucket"

  destination:
    daily: "s3://harbor-destination-backup/daily"
    weekly: "s3://harbor-destination-backup/weekly"
    monthly: "s3://harbor-destination-backup/monthly"

  schedule:
    daily: "12 12 * * *"   # Every day @ 12:12 (add smear)
    weekly: "2 9 * * 1"   # Every Monday @ 9:02
    monthly: "17 16 1 * *" # 1st of month @ 16:17 