apiVersion: v2
dependencies:
  - repository: https://opensearch-project.github.io/opensearch-k8s-operator/
    name: opensearch-operator
    version: 2.8.2
  - repository: https://opensearch-project.github.io/opensearch-k8s-operator/
    name: opensearch-cluster
    version: 3.2.1
description: A Helm chart to deploy an opinionated opensearch cluster with IRIS-IAM integration
name: stfc-cloud-opensearch
type: application
version: 3.1.0
